### ISSUE TITLE
Checklist for User Research to Berlin Design Sprint

### ISSUE THREAD

**Issue by thornet** [MozillaFoundation/iot#21]
- [x] March 14: Begin user research. Read more about the insight missions and user research process. Begin expert interviews. 
- [x] March 28: End user research. Expert interviews cont.  
- [ ] April 4: 1:1 interviews with each participant. Include expert interview where relevant. 
- [ ] April 11: Circulate scenarios among participants and upvote compelling ones. 
- [ ] April 18: Refine scenarios and invite participants to enrich them in teams. 
- [ ] April 22 - 25: Design sprint in Berlin using the scenarios as a design brief.
- [ ] April 26: Debrief and documentation.

**Comment by ileddigital** [comment]
@thornet I've opened a google doc here for Babitha, myself and you to share initial ideas as they arise from the research. 

https://docs.google.com/document/d/19r96BoTCrDoLIMijHaaNuMo4GJ5gC-16C--daOdlqPQ/edit
